Add related work
fkie-cad/intrusion-detection-datasets pull request #12
Opened 2024-02-19 14:23 UTC by Maspital

Resolves #10 

Adds said page, covering numerous related surveys and collections.
We could consider covering collections in a separate page/table for easier accessibility.

Also includes changes from the hotfix branch, which simply fix some broken links, missing or incorrect info, etc.

2024-02-20 09:11 UTC, ru37z commented
Reminder to myself: Do not merge until blog post is added. :)

2024-02-20 10:21 UTC, ru37z requested changes
Overall awesome work, thank you! Here are some minor change requests.

2024-02-21 10:11 UTC, Maspital commented on content/related_work.md
> +
Removing these newlines does sadly not change the amount of white space that appears on the website

2024-02-21 12:34 UTC, ru37z approved these changes

2024-02-21 12:35 UTC, merged